### ISSUE TITLE
Cannot set up TightConcat for VSCODE 

### ISSUE THREAD

**Issue by nghitrum** [phpfmt-next/fmt#4]
Description:
It should be a way to make a configuration for this option. I tried to find documents but there is none of them. I need to read to phar file to find the keyword TightConcat.

The problem is when I format the php file, vscode adds 2 extra spaces before and after the dot (period) operator for concatenation.

Example code:
```
return $this->getProjectDir() . '/var/log';
```

My configuration:
```
phpfmt.custom_arguments: "TightConcat"
```

**Comment by kokororin** [comment]
It is documented: 
```
"phpfmt.passes": ["TightConcat"]
```
