### ISSUE TITLE
Few questions about vscode extensions

### ISSUE THREAD

**Issue by elieobeid7** [phpfmt-next/fmt#5]
- How to remove empty lines in pure php file or one containing html

- How to format all files on Git commit?

**Comment by kokororin** [comment]
* There is no such AdditionalPass, but you can try `StripNewlineAfterClassOpen `, `StripNewlineAfterCurlyOpen`,  `StripNewlineWithinClassBody `.
* Create a script like [this](https://github.com/phpfmt-next/fmt/blob/master/scripts/format.php), it use the [config file](https://github.com/phpfmt-next/fmt/blob/master/.phpfmt.ini), and install some package like [brainmaestro/composer-git-hooks](https://packagist.org/packages/brainmaestro/composer-git-hooks) to trigger the below format script on git commit.

**Comment by elieobeid7** [comment]
Thank you
