### ISSUE TITLE
phpfmt.indent_with_space: false  uses spaces, not tabs in VS Code 

### ISSUE THREAD

**Issue by dpatty** [phpfmt-next/fmt#7]
## Description:
* install phpfmt - PHP formatter in VSCode. 
* open a php file with indentation
* Run `> phpfmt: format this file`
Expected result: indentation uses Tabs, not spaces
Actual result: indentation uses spaces (4), not tabs.

### User Settings
```
    "phpfmt.indent_with_space": false
```

with PHP v7.1

```
$ php -v
PHP 7.1.14 (cli) (built: Feb  2 2018 08:41:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by shamseerahammedm** [comment]
" phpfmt: cannot find php bin " how do i solve this , still getting this error even after pointing the executable path - this is how my settings looks like..
{
"php.validate.executablePath": "C://Program Files//php//php.exe", 
 "phpfmt.php_bin" :"C://Program Files//php//php.exe",
}

**Comment by kokororin** [comment]
`phpfmt.detect_intent: true`
